### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by CYCLOP5**

### CODE REVIEW

**Comment by CYCLOP5** [comment]
merge this after review

**Comment by CYCLOP5** [comment]
ill make a good readme tonight

**Comment by Th3C0d3Mast3r** [comment]
> ill make a good readme tonight

GPT makes em good-I used for some of my recent projects and they seemed good. Do give that a try-like copy-past some codes and all, with a bit of description, and all

**Comment by Aaryan-Urunkar** [comment]
LGTM!

**Pull request merged**
